-- ============================================================
-- Settly – Migración v3: planes (entitlements) + códigos de acceso
-- Ejecuta en Supabase → SQL Editor → New query
--
-- Habilita la fase de prueba SIN Stripe: el acceso Pro se concede
-- canjeando un código. El plan vive en `entitlements` y SOLO lo puede
-- escribir la función `redeem_access_code` (SECURITY DEFINER), así que
-- un usuario no puede auto-activarse Pro desde el cliente.
-- Cuando se integre Stripe, su webhook escribirá en esta misma tabla.
-- ============================================================

-- 1. Entitlements: el plan de cada usuario (fuente de verdad)
CREATE TABLE IF NOT EXISTS entitlements (
  user_id    UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  plan       TEXT NOT NULL DEFAULT 'free',   -- 'free' | 'pro'
  expires_at TIMESTAMPTZ,                     -- NULL = sin caducidad
  source     TEXT,                            -- 'code' | 'stripe' | ...
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE entitlements ENABLE ROW LEVEL SECURITY;

-- El usuario solo puede LEER su propio entitlement. No hay políticas de
-- INSERT/UPDATE: nadie escribe directamente; solo la función definer.
DROP POLICY IF EXISTS "read own entitlement" ON entitlements;
CREATE POLICY "read own entitlement" ON entitlements FOR SELECT
  USING (user_id = auth.uid());

-- 2. Códigos de acceso
CREATE TABLE IF NOT EXISTS access_codes (
  code          TEXT PRIMARY KEY,
  grants_plan   TEXT NOT NULL DEFAULT 'pro',
  duration_days INT,                          -- NULL = sin caducidad (beta)
  max_uses      INT,                          -- NULL = ilimitado
  uses          INT NOT NULL DEFAULT 0,
  active        BOOLEAN NOT NULL DEFAULT TRUE,
  expires_at    TIMESTAMPTZ,                  -- el código deja de valer tras esto
  note          TEXT,
  created_at    TIMESTAMPTZ DEFAULT NOW()
);

-- RLS activado y SIN políticas → los usuarios no pueden leer ni listar
-- los códigos (no se filtran). La función definer sí accede.
ALTER TABLE access_codes ENABLE ROW LEVEL SECURITY;

-- 3. Registro de canjes (un código por usuario)
CREATE TABLE IF NOT EXISTS code_redemptions (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code        TEXT NOT NULL REFERENCES access_codes(code) ON DELETE CASCADE,
  user_id     UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  redeemed_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (code, user_id)
);

ALTER TABLE code_redemptions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "read own redemptions" ON code_redemptions;
CREATE POLICY "read own redemptions" ON code_redemptions FOR SELECT
  USING (user_id = auth.uid());

-- 4. Función de canje (valida y concede el plan de forma atómica)
CREATE OR REPLACE FUNCTION redeem_access_code(p_code TEXT)
RETURNS JSONB
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_uid     UUID := auth.uid();
  v_code    access_codes%ROWTYPE;
  v_expires TIMESTAMPTZ;
BEGIN
  IF v_uid IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'error', 'not_authenticated');
  END IF;

  SELECT * INTO v_code FROM access_codes
   WHERE code = upper(trim(p_code)) FOR UPDATE;

  IF NOT FOUND OR NOT v_code.active THEN
    RETURN jsonb_build_object('ok', false, 'error', 'invalid');
  END IF;
  IF v_code.expires_at IS NOT NULL AND v_code.expires_at < NOW() THEN
    RETURN jsonb_build_object('ok', false, 'error', 'expired');
  END IF;
  IF v_code.max_uses IS NOT NULL AND v_code.uses >= v_code.max_uses THEN
    RETURN jsonb_build_object('ok', false, 'error', 'exhausted');
  END IF;

  -- Ya canjeado por este usuario → éxito idempotente
  IF EXISTS (SELECT 1 FROM code_redemptions WHERE code = v_code.code AND user_id = v_uid) THEN
    RETURN jsonb_build_object('ok', true, 'plan', v_code.grants_plan, 'already', true);
  END IF;

  v_expires := CASE
    WHEN v_code.duration_days IS NULL THEN NULL
    ELSE NOW() + (v_code.duration_days || ' days')::interval
  END;

  INSERT INTO code_redemptions (code, user_id) VALUES (v_code.code, v_uid);
  UPDATE access_codes SET uses = uses + 1 WHERE code = v_code.code;

  INSERT INTO entitlements (user_id, plan, expires_at, source, updated_at)
  VALUES (v_uid, v_code.grants_plan, v_expires, 'code', NOW())
  ON CONFLICT (user_id) DO UPDATE
    SET plan = EXCLUDED.plan, expires_at = EXCLUDED.expires_at,
        source = EXCLUDED.source, updated_at = NOW();

  RETURN jsonb_build_object('ok', true, 'plan', v_code.grants_plan, 'expires_at', v_expires);
END;
$$;

GRANT EXECUTE ON FUNCTION redeem_access_code(TEXT) TO authenticated;

-- 5. Código de ejemplo para la beta (ilimitado, sin caducidad).
--    Crea los tuyos con, p.ej.:
--    INSERT INTO access_codes (code, duration_days, max_uses, note)
--    VALUES ('AMIGO-2026', 90, 50, 'lote amigos');
INSERT INTO access_codes (code, grants_plan, duration_days, max_uses, note)
VALUES ('SETTLYBETA', 'pro', NULL, NULL, 'beta abierta')
ON CONFLICT (code) DO NOTHING;
