-- ============================================================
-- Settly — Setup completo (idempotente)
-- Pega esto en Supabase → SQL Editor → New query → Run.
-- Incluye: perfiles, grupos, miembros, invite links, planes
-- (entitlements) y códigos de acceso. Seguro de re-ejecutar.
-- ============================================================

-- ---------- PERFILES ----------
CREATE TABLE IF NOT EXISTS profiles (
  id         UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  name       TEXT NOT NULL DEFAULT '',
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE profiles
  ADD COLUMN IF NOT EXISTS email          TEXT    NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS phone          TEXT    NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS phone_verified BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS avatar         TEXT    NOT NULL DEFAULT '';

-- Crea el perfil automáticamente al registrarse (incluye email)
CREATE OR REPLACE FUNCTION handle_new_user()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  INSERT INTO public.profiles (id, name, email)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'name', NEW.raw_user_meta_data->>'full_name', ''),
    COALESCE(NEW.email, '')
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION handle_new_user();

-- Sincroniza emails de usuarios ya existentes
UPDATE public.profiles p
SET email = u.email
FROM auth.users u
WHERE p.id = u.id AND p.email = '';

-- ---------- GRUPOS ----------
CREATE TABLE IF NOT EXISTS groups (
  id         TEXT PRIMARY KEY,
  owner_id   UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  data       JSONB NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS group_members (
  group_id  TEXT NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
  user_id   UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  member_id TEXT NOT NULL,
  PRIMARY KEY (group_id, user_id)
);

CREATE TABLE IF NOT EXISTS invite_links (
  token      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  group_id   TEXT NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
  created_by UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  expires_at TIMESTAMPTZ NOT NULL DEFAULT (NOW() + INTERVAL '7 days'),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ---------- PLANES + CÓDIGOS ----------
CREATE TABLE IF NOT EXISTS entitlements (
  user_id    UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  plan       TEXT NOT NULL DEFAULT 'free',   -- 'free' | 'pro'
  expires_at TIMESTAMPTZ,
  source     TEXT,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS access_codes (
  code          TEXT PRIMARY KEY,
  grants_plan   TEXT NOT NULL DEFAULT 'pro',
  duration_days INT,
  max_uses      INT,
  uses          INT NOT NULL DEFAULT 0,
  active        BOOLEAN NOT NULL DEFAULT TRUE,
  expires_at    TIMESTAMPTZ,
  note          TEXT,
  created_at    TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS code_redemptions (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code        TEXT NOT NULL REFERENCES access_codes(code) ON DELETE CASCADE,
  user_id     UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  redeemed_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (code, user_id)
);

-- ---------- ROW LEVEL SECURITY ----------
ALTER TABLE profiles         ENABLE ROW LEVEL SECURITY;
ALTER TABLE groups           ENABLE ROW LEVEL SECURITY;
ALTER TABLE group_members    ENABLE ROW LEVEL SECURITY;
ALTER TABLE invite_links     ENABLE ROW LEVEL SECURITY;
ALTER TABLE entitlements     ENABLE ROW LEVEL SECURITY;
ALTER TABLE access_codes     ENABLE ROW LEVEL SECURITY;
ALTER TABLE code_redemptions ENABLE ROW LEVEL SECURITY;

-- Perfiles: lectura entre usuarios (para invitar); escritura solo el propio
DROP POLICY IF EXISTS "Own profile"     ON profiles;
DROP POLICY IF EXISTS "Read profiles"   ON profiles;
DROP POLICY IF EXISTS "Insert own profile" ON profiles;
DROP POLICY IF EXISTS "Update own profile" ON profiles;
CREATE POLICY "Read profiles"       ON profiles FOR SELECT USING (auth.uid() IS NOT NULL);
CREATE POLICY "Insert own profile"  ON profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Update own profile"  ON profiles FOR UPDATE USING (auth.uid() = id) WITH CHECK (auth.uid() = id);

-- Grupos
DROP POLICY IF EXISTS "Members view groups"        ON groups;
DROP POLICY IF EXISTS "Members update groups"      ON groups;
DROP POLICY IF EXISTS "Authenticated insert groups" ON groups;
DROP POLICY IF EXISTS "Owner delete groups"        ON groups;
CREATE POLICY "Members view groups" ON groups FOR SELECT
  USING (
    owner_id = auth.uid()
    OR EXISTS (SELECT 1 FROM group_members WHERE group_id = groups.id AND user_id = auth.uid())
    OR EXISTS (SELECT 1 FROM invite_links   WHERE group_id = groups.id AND expires_at > NOW())
  );
CREATE POLICY "Members update groups" ON groups FOR UPDATE
  USING (EXISTS (SELECT 1 FROM group_members WHERE group_id = groups.id AND user_id = auth.uid()));
CREATE POLICY "Authenticated insert groups" ON groups FOR INSERT
  WITH CHECK (auth.uid() = owner_id);
CREATE POLICY "Owner delete groups" ON groups FOR DELETE
  USING (auth.uid() = owner_id);

-- Miembros
-- Helper SECURITY DEFINER: ¿soy miembro de este grupo? Evita la recursión de RLS
-- al consultar group_members dentro de su propia política (ver migrate_v4).
CREATE OR REPLACE FUNCTION public.is_member_of(gid text)
RETURNS boolean LANGUAGE sql SECURITY DEFINER STABLE SET search_path = public AS $$
  SELECT EXISTS (SELECT 1 FROM group_members WHERE group_id = gid AND user_id = auth.uid());
$$;
GRANT EXECUTE ON FUNCTION public.is_member_of(text) TO authenticated;

DROP POLICY IF EXISTS "View own memberships" ON group_members;
DROP POLICY IF EXISTS "View co-members"      ON group_members;
DROP POLICY IF EXISTS "Join group"           ON group_members;
DROP POLICY IF EXISTS "Leave group"          ON group_members;
CREATE POLICY "View own memberships" ON group_members FOR SELECT
  USING (user_id = auth.uid());
-- Leer co-miembros de tus grupos (para "Tu red"/sugeridos). Se combina con la
-- anterior vía OR; no afecta INSERT/DELETE.
CREATE POLICY "View co-members" ON group_members FOR SELECT
  USING (public.is_member_of(group_id));
CREATE POLICY "Join group" ON group_members FOR INSERT
  WITH CHECK (
    (user_id = auth.uid()
      AND EXISTS (SELECT 1 FROM invite_links WHERE group_id = group_members.group_id AND expires_at > NOW()))
    OR (user_id = auth.uid()
      AND EXISTS (SELECT 1 FROM groups WHERE id = group_id AND owner_id = auth.uid()))
    OR (user_id != auth.uid()
      AND EXISTS (SELECT 1 FROM group_members gm WHERE gm.group_id = group_members.group_id AND gm.user_id = auth.uid()))
  );
CREATE POLICY "Leave group" ON group_members FOR DELETE
  USING (user_id = auth.uid());

-- Invite links
DROP POLICY IF EXISTS "Auth users view invites" ON invite_links;
DROP POLICY IF EXISTS "Members create invites"  ON invite_links;
CREATE POLICY "Auth users view invites" ON invite_links FOR SELECT
  USING (auth.uid() IS NOT NULL);
CREATE POLICY "Members create invites" ON invite_links FOR INSERT
  WITH CHECK (
    auth.uid() = created_by
    AND EXISTS (SELECT 1 FROM group_members WHERE group_id = invite_links.group_id AND user_id = auth.uid())
  );

-- Entitlements: el usuario solo lee el suyo (nadie escribe directo)
DROP POLICY IF EXISTS "read own entitlement" ON entitlements;
CREATE POLICY "read own entitlement" ON entitlements FOR SELECT
  USING (user_id = auth.uid());

-- access_codes: RLS activado y SIN políticas → nadie puede leer los códigos
-- Canjes: el usuario ve los suyos
DROP POLICY IF EXISTS "read own redemptions" ON code_redemptions;
CREATE POLICY "read own redemptions" ON code_redemptions FOR SELECT
  USING (user_id = auth.uid());

-- ---------- FUNCIÓN DE CANJE (segura) ----------
CREATE OR REPLACE FUNCTION redeem_access_code(p_code TEXT)
RETURNS JSONB
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_uid     UUID := auth.uid();
  v_code    access_codes%ROWTYPE;
  v_expires TIMESTAMPTZ;
BEGIN
  IF v_uid IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'error', 'not_authenticated');
  END IF;

  SELECT * INTO v_code FROM access_codes
   WHERE code = upper(trim(p_code)) FOR UPDATE;

  IF NOT FOUND OR NOT v_code.active THEN
    RETURN jsonb_build_object('ok', false, 'error', 'invalid');
  END IF;
  IF v_code.expires_at IS NOT NULL AND v_code.expires_at < NOW() THEN
    RETURN jsonb_build_object('ok', false, 'error', 'expired');
  END IF;
  IF v_code.max_uses IS NOT NULL AND v_code.uses >= v_code.max_uses THEN
    RETURN jsonb_build_object('ok', false, 'error', 'exhausted');
  END IF;

  IF EXISTS (SELECT 1 FROM code_redemptions WHERE code = v_code.code AND user_id = v_uid) THEN
    RETURN jsonb_build_object('ok', true, 'plan', v_code.grants_plan, 'already', true);
  END IF;

  v_expires := CASE
    WHEN v_code.duration_days IS NULL THEN NULL
    ELSE NOW() + (v_code.duration_days || ' days')::interval
  END;

  INSERT INTO code_redemptions (code, user_id) VALUES (v_code.code, v_uid);
  UPDATE access_codes SET uses = uses + 1 WHERE code = v_code.code;

  INSERT INTO entitlements (user_id, plan, expires_at, source, updated_at)
  VALUES (v_uid, v_code.grants_plan, v_expires, 'code', NOW())
  ON CONFLICT (user_id) DO UPDATE
    SET plan = EXCLUDED.plan, expires_at = EXCLUDED.expires_at,
        source = EXCLUDED.source, updated_at = NOW();

  RETURN jsonb_build_object('ok', true, 'plan', v_code.grants_plan, 'expires_at', v_expires);
END;
$$;

GRANT EXECUTE ON FUNCTION redeem_access_code(TEXT) TO authenticated;

-- ---------- CÓDIGO DE BETA DE EJEMPLO ----------
INSERT INTO access_codes (code, grants_plan, duration_days, max_uses, note)
VALUES ('SETTLYBETA', 'pro', NULL, NULL, 'beta abierta')
ON CONFLICT (code) DO NOTHING;
